import { defineConfig } from 'unocss'

export default defineConfig({
    rules: [
        // Catppuccin Mocha Backgrounds
        ['bg-rosewater', {background: "#f5e0dc"}],
        ['bg-flamingo', {background: "#f2cdcd"}],
        ['bg-pink', {background: "#f2cdcd"}],
        ['bg-mauve', {background: "#cba6f7"}],
        ['bg-red', {background: "#f38ba8"}],
        ['bg-maroon', {background: "#eba0ac"}],
        ['bg-peach', {background: "#fab387"}],
        ['bg-yellow', {background: "#f9e2af"}],
        ['bg-green', {background: "#a6e3a1"}],
        ['bg-teal', {background: "#94e2d5"}],
        ['bg-sky', {background: "#89dceb"}],
        ['bg-sapphine', {background: "#74c7ec"}],
        ['bg-blue', {background: "#89b4fa"}],
        ['bg-lavender', {background: "#b4befe"}],
        ['bg-text', {background: "#cdd6f4"}],
        ['bg-subtext1', {background: "#bac2de"}],
        ['bg-subtext0', {background: "#a6adc8"}],
        ['bg-overlay2', {background: "#9399b2"}],
        ['bg-overlay1', {background: "#7f849c"}],
        ['bg-overlay0', {background: "#6c7086"}],
        ['bg-surface2', {background: "#585b70"}],
        ['bg-surface1', {background: "#45475a"}],
        ['bg-surface0', {background: "#313244"}],
        ['bg-base', {background: "#1e1d2d"}],
        ['bg-mantle', {background: "#181825"}],
        ['bg-crust', { background: "#11111b" }],
        // Catppuccin Mocha colors
        ['fg-rosewater', {color: "#f5e0dc"}],
        ['fg-flamingo', {color: "#f2cdcd"}],
        ['fg-pink', {color: "#f2cdcd"}],
        ['fg-mauve', {color: "#cba6f7"}],
        ['fg-red', {color: "#f38ba8"}],
        ['fg-maroon', {color: "#eba0ac"}],
        ['fg-peach', {color: "#fab387"}],
        ['fg-yellow', {color: "#f9e2af"}],
        ['fg-green', {color: "#a6e3a1"}],
        ['fg-teal', {color: "#94e2d5"}],
        ['fg-sky', {color: "#89dceb"}],
        ['fg-sapphine', {color: "#74c7ec"}],
        ['fg-blue', {color: "#89b4fa"}],
        ['fg-lavender', {color: "#b4befe"}],
        ['fg-text', {color: "#cdd6f4"}],
        ['fg-subtext1', {color: "#bac2de"}],
        ['fg-subtext0', {color: "#a6adc8"}],
        ['fg-overlay2', {color: "#9399b2"}],
        ['fg-overlay1', {color: "#7f849c"}],
        ['fg-overlay0', {color: "#6c7086"}],
        ['fg-surface2', {color: "#585b70"}],
        ['fg-surface1', {color: "#45475a"}],
        ['fg-surface0', {color: "#313244"}],
        ['fg-base', {color: "#1e1d2d"}],
        ['fg-mantle', {color: "#181825"}],
        ['fg-crust', { color: "#11111b" }],
        // Fonts
        ['font-roboto', {'font-family': '"Roboto"'}],
        ['font-inter', {'font-family': '"Inter"'}]
    ]
})