import { defineConfig } from 'unocss'

export default defineConfig({
    rules: [
       // Catppuccin Mocha Backgrounds
       ['bg-rosewater', {background: "#f5e0dc"}],
       ['bg-flamingo', {background: "#f2cdcd"}],
       ['bg-pink', {background: "#f2cdcd"}],
       ['bg-mauve', {background: "#f2cdcd"}],
       ['bg-red', {background: "#f38ba8"}],
       ['bg-maroon', {background: "#eba0ac"}],
       ['bg-peach', {background: "#fab387"}],
       ['bg-yellow', {background: "#f9e2af"}],
       ['bg-green', {background: "#a6e3a1"}],
       ['bg-teal', {background: "#94e2d5"}],
       ['bg-sky', {background: "#89dceb"}],
       ['bg-sapphine', {background: "#74c7ec"}],
       ['bg-blue', {background: "#89b4fa"}],
       ['bg-lavender', {background: "#b4befe"}],
       ['bg-text', {background: "#cdd6f4"}],
       ['bg-subtext1', {background: "#bac2de"}],
       ['bg-subtext0', {background: "#a6adc8"}],
       ['bg-overlay2', {background: "#9399b2"}],
       ['bg-overlay1', {background: "#7f849c"}],
       ['bg-overlay0', {background: "#6c7086"}],
       ['bg-surface2', {background: "#585b70"}],
       ['bg-surface1', {background: "#45475a"}],
       ['bg-surface0', {background: "#313244"}],
       ['bg-base', {background: "#1e1d2d"}],
       ['bg-mantle', {background: "#181825"}],
        ['bg-crust', { background: "#11111b" }],
       // Catppuccin Mocha Foregrounds
       ['fg-rosewater', {foreground: "#f5e0dc"}],
       ['fg-flamingo', {foreground: "#f2cdcd"}],
       ['fg-pink', {foreground: "#f2cdcd"}],
       ['fg-mauve', {foreground: "#f2cdcd"}],
       ['fg-red', {foreground: "#f38ba8"}],
       ['fg-maroon', {foreground: "#eba0ac"}],
       ['fg-peach', {foreground: "#fab387"}],
       ['fg-yellow', {foreground: "#f9e2af"}],
       ['fg-green', {foreground: "#a6e3a1"}],
       ['fg-teal', {foreground: "#94e2d5"}],
       ['fg-sky', {foreground: "#89dceb"}],
       ['fg-sapphine', {foreground: "#74c7ec"}],
       ['fg-blue', {foreground: "#89b4fa"}],
       ['fg-lavender', {foreground: "#b4befe"}],
       ['fg-text', {foreground: "#cdd6f4"}],
       ['fg-subtext1', {foreground: "#bac2de"}],
       ['fg-subtext0', {foreground: "#a6adc8"}],
       ['fg-overlay2', {foreground: "#9399b2"}],
       ['fg-overlay1', {foreground: "#7f849c"}],
       ['fg-overlay0', {foreground: "#6c7086"}],
       ['fg-surface2', {foreground: "#585b70"}],
       ['fg-surface1', {foreground: "#45475a"}],
       ['fg-surface0', {foreground: "#313244"}],
       ['fg-base', {foreground: "#1e1d2d"}],
       ['fg-mantle', {foreground: "#181825"}],
       ['fg-crust', {foreground: "#11111b"}],
    ]
})