<template>
    <div class="flex flex-col fg-text w-full min-h-screen">
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
        <span>home</span>
    </div>
</template>